# Generated by Django 3.2 on 2023-07-08 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Visitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visitorSessionName', models.CharField(max_length=250)),
                ('visit_date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
