# Generated by Django 4.2.3 on 2023-07-29 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0004_visitor_visit_darkmode_state'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('testimonial', models.CharField(max_length=300)),
                ('testimonial_by', models.CharField(max_length=20)),
            ],
        ),
    ]
