# Generated by Django 4.2.3 on 2023-07-29 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0005_testimonial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReachOut',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=320)),
                ('last_name', models.CharField(max_length=320)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('message', models.CharField(max_length=500)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
