# Generated by Django 4.2.3 on 2023-07-15 20:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Projects', '0002_alter_project_brief_description_alter_project_name'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Image',
            new_name='CustomImage',
        ),
    ]
