# Generated by Django 4.2.3 on 2023-10-04 08:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254)),
                ('service_description', models.TextField(max_length=508)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('slug', models.SlugField(blank=True, max_length=255, null=True, unique=True)),
            ],
            options={
                'verbose_name': 'Service',
                'verbose_name_plural': 'Services',
            },
        ),
        migrations.CreateModel(
            name='SubServiceImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='sub_service-images/')),
            ],
        ),
        migrations.CreateModel(
            name='Sub_Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254)),
                ('sub_service_description', models.TextField(max_length=508)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('slug', models.SlugField(blank=True, max_length=255, null=True, unique=True)),
                ('image', models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_service_image', to='services.subserviceimage')),
                ('services', models.ManyToManyField(blank=True, null=True, related_name='sub_services', to='services.service')),
            ],
            options={
                'verbose_name': 'Sub Service',
                'verbose_name_plural': 'Sub Services',
            },
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=508, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('extra_notes', models.TextField(null=True)),
                ('slug', models.SlugField(blank=True, max_length=255, null=True, unique=True)),
                ('location', models.CharField(max_length=508, null=True)),
                ('date', models.CharField(max_length=100, null=True)),
                ('services', models.ManyToManyField(blank=True, related_name='sub_services_orders', to='services.sub_service')),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
            },
        ),
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=254)),
                ('last_name', models.CharField(max_length=254)),
                ('phone_number', models.CharField(max_length=254)),
                ('email', models.EmailField(max_length=254)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customer_order', to='services.orders')),
            ],
            options={
                'verbose_name': 'Customer',
                'verbose_name_plural': 'Customers',
            },
        ),
    ]
