# Generated by Django 4.2.3 on 2023-07-30 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sub_service',
            old_name='service_description',
            new_name='sub_service_description',
        ),
    ]
