# Generated by Django 4.2.3 on 2023-07-30 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_rename_service_description_sub_service_sub_service_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='services',
        ),
        migrations.AddField(
            model_name='sub_service',
            name='services',
            field=models.ManyToManyField(blank=True, related_name='sub_services', to='services.service'),
        ),
    ]
