# Generated by Django 4.2.3 on 2023-07-30 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_remove_service_services_sub_service_services'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sub_service',
            name='services',
            field=models.ManyToManyField(blank=True, null=True, related_name='sub_services', to='services.service'),
        ),
    ]
