# Generated by Django 4.2.3 on 2023-09-13 22:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0006_reachout'),
        ('services', '0005_orders'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='order_code',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='services',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='slug',
        ),
        migrations.AddField(
            model_name='orders',
            name='code',
            field=models.CharField(max_length=508, null=True),
        ),
        migrations.AddField(
            model_name='orders',
            name='extra_notes',
            field=models.TextField(null=True),
        ),
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=254)),
                ('last_name', models.CharField(max_length=254)),
                ('phone_number', models.CharField(max_length=254)),
                ('email', models.EmailField(max_length=254)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='services.orders')),
            ],
            options={
                'verbose_name': 'Customer',
                'verbose_name_plural': 'Customers',
            },
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=508, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('services', models.ManyToManyField(blank=True, related_name='sub_services_orders', to='services.sub_service')),
                ('visitor', models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, to='general.visitor')),
            ],
            options={
                'verbose_name': 'Cart',
                'verbose_name_plural': 'Carts',
            },
        ),
        migrations.AddField(
            model_name='orders',
            name='cart',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='services.cart'),
        ),
    ]
